name: FSMTP Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-python@v1
  - uses: BSFishy/meson-build@v1.0.1
    with:
      action: test
  
  -name: MkBuild
  -run: meson build

  -name: ChangeDir
  -run: cd build
   
  -name: Build
  -run: ninja
.
